# Generated by Django 5.2.10 on 2026-01-19 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Ekipman Kategorisi',
                'verbose_name_plural': 'Ekipman Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='EquipmentReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('active', 'Aktif (Teslim Alındı)'), ('completed', 'Tamamlandı (İade Edildi)'), ('cancelled', 'İptal')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rezervasyon',
                'verbose_name_plural': 'Rezervasyonlar',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Ekipman Adı')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seri No')),
                ('qr_code', models.CharField(max_length=255, unique=True, verbose_name='QR Code Data')),
                ('status', models.CharField(choices=[('available', 'Müsait'), ('in_use', 'Kullanımda/Sahada'), ('maintenance', 'Bakımda'), ('retired', 'Hurda/Emekli')], default='available', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Ekipman',
                'verbose_name_plural': 'Ekipmanlar',
            },
        ),
    ]
