# Generated by Django 5.2.10 on 2026-01-19 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'Yapılacak'), ('in_progress', 'Devam Ediyor'), ('review', 'Kontrol'), ('done', 'Tamamlandı')], default='todo', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('time_estimate_minutes', models.IntegerField(default=0, help_text='Tahmini süre (dk)')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='agencies.agency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
